# Generated by Django 5.2.11 on 2026-02-28 16:01
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_tags"),
    ]

    operations = [TrigramExtension()]
